version: "3"
services:
  frontend:
    container_name: cuddly_carnival_frontend_dev
    image: cuddly-carnival-frontend-dev:1.0.0
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    networks:
      - cuddly-network
    volumes: 
      - ./frontend/:/app
      - /app/node_modules

  backend:
    container_name: cuddly_carnival_backend_dev
    image: cuddly-carnival-backend-dev:1.0.0
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 3001:3000
    networks:
      - cuddly-network
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

networks:
  cuddly-network: